menu:
  Home: /
  Archives: /archives
  About: /about

widgets:
- search
## the search box
- category
## category
- recent_posts
## your recent posts show
- tagcloud
## the tag of your articles with an effect of wordcloud

- blogroll
## friendly link

blogroll:
  Github: https://github.com/

excerpt_link: Continue Reading

comment:
  # disqus: 
  # disqus_shortname: 
## to enable disqus, you need to fill in the disqus_shortname in config.yml

## share plugins at the bottom of the article
share:
  enable: true
  jiathis: true

bottom_link:
  github: forcemain

logo:
  enable: true  
  ## display img
  src: img/favicon.png 
  ## 32 * 32px, logo img
  apple_icon: img/apple-icon.ico 
  ## logo img for apple icon, 114 * 114 px

## your personal page, could be your github account page, twitter or google plus personal page
## By default its your homepage
personal_site: /

addthis:
  enable: true
  pubid: 
  facebook: true
  twitter: true
  google: true

fancybox: false

## you can change the custom font in head.ejs
CustomFont: true

## url of your rss
## it is highly recommanded to use rss plugins, https://github.com/hexojs/hexo-generator-feed
rss: /atom.xml

## for Chinese users
ChineseUser: true
